Debug Dockerfile

diff --git a/.devcontainer/Dockerfile b/.devcontainer/Dockerfile
--- a/.devcontainer/Dockerfile
+++ b/.devcontainer/Dockerfile
@@ -9,9 +9,10 @@ FROM registry.opensuse.org/opensuse/tumbleweed:latest
 
 # Run the script
 #RUN /run/install-dependency.sh
-
+RUN zypper lr
 RUN zypper dup -y
-RUN zypper in -y os-autoinst-distri-opensuse-deps-worker perl-JSON-Validator gnu_parallel
+RUN zypper lr
+RUN zypper in -y os-autoinst-distri-opensuse-deps-worker perl-JSON-Validator gnu_parallel || echo "---zypper failure---"
 RUN zypper in -y make git vim gcc-c++ libxml2-devel libssh2-devel libexpat-devel dbus-1-devel python311 python311-devel python311-yamllint python311-PyYAML perl-App-cpanminus perl-Code-TidyAll
 RUN echo "---###---   ---###---"
 RUN pwd
